[build]
  command = "cd src/frontend && npm install && npm run build"
  publish = "src/frontend/dist"
  functions = "netlify/functions"

[dev]
  command = "npm --prefix src/frontend run dev"
  port = 8888
  targetPort = 5173
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
