/**
 * transitScenarioPresets.js — Seed data for demo scenarios.
 * Each preset showcases different corridor tradeoffs.
 */

import { buildCorridorLineGeometry } from '../../shared/presetCorridors.js'

export const PHOENIX_SCENARIO = {
  cityId: 'phoenix',
  projectName: 'West Phoenix Light Rail Extension',
  planningGoal: 'lowest carbon with manageable disruption',
  corridors: [
    {
      id: 'alt-a',
      name: 'Alt A - 19th Ave Median Running',
      description: 'Primarily at-grade median with one elevated crossing at I-17',
      geometry: buildCorridorLineGeometry('phoenix', 'alt-a'),
      segments: [
        {
          id: 'a-1',
          label: '19th Ave at-grade (Camelback to McDowell)',
          segmentType: 'at_grade_median',
          sectionFamily: 'conventional_rc',
          lengthFt: 8400,
          context: 'urban_arterial',
          factors: {
            trafficAadt: 28000,
            intersectionDensityPerMi: 6,
            utilityDensityHigh: false,
            trafficSensitivityHigh: false,
            constrainedRow: false,
            floodRisk: 'low',
            urbanCore: false,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 7,
            jobCatchment: 5,
            zeroCarHouseholdsPct: 6,
            transferConnectivity: 4,
            activityNodeImportance: 5,
            heatExposureHigh: true,
            stationTransferStrong: false,
          },
        },
        {
          id: 'a-2',
          label: 'I-17 elevated crossing',
          segmentType: 'elevated_crossing',
          sectionFamily: 'conventional_rc',
          lengthFt: 1800,
          context: 'urban_arterial',
          factors: {
            trafficAadt: 35000,
            intersectionDensityPerMi: 2,
            utilityDensityHigh: true,
            trafficSensitivityHigh: true,
            constrainedRow: true,
            floodRisk: 'low',
            urbanCore: false,
            nightWorkOnly: true,
          },
          community: {
            populationCatchment: 3,
            jobCatchment: 4,
            zeroCarHouseholdsPct: 5,
            transferConnectivity: 2,
            activityNodeImportance: 3,
            heatExposureHigh: true,
            stationTransferStrong: false,
          },
        },
        {
          id: 'a-3',
          label: 'Thomas Rd station zone',
          segmentType: 'station_zone',
          sectionFamily: 'conventional_rc',
          lengthFt: 1200,
          context: 'urban_arterial',
          factors: {
            trafficAadt: 22000,
            intersectionDensityPerMi: 10,
            utilityDensityHigh: false,
            trafficSensitivityHigh: false,
            constrainedRow: false,
            floodRisk: 'low',
            urbanCore: false,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 8,
            jobCatchment: 6,
            zeroCarHouseholdsPct: 7,
            transferConnectivity: 6,
            activityNodeImportance: 7,
            heatExposureHigh: true,
            stationTransferStrong: true,
          },
        },
      ],
    },
    {
      id: 'alt-b',
      name: 'Alt B - Central Ave FRC Option',
      description: 'Fiber-reinforced thinner slab on Central Ave, lower carbon but urban street context',
      geometry: buildCorridorLineGeometry('phoenix', 'alt-b'),
      segments: [
        {
          id: 'b-1',
          label: 'Central Ave embedded (Camelback to Roosevelt)',
          segmentType: 'embedded_urban_street',
          sectionFamily: 'fiber_reduced',
          lengthFt: 10500,
          context: 'urban_core',
          factors: {
            trafficAadt: 32000,
            intersectionDensityPerMi: 12,
            utilityDensityHigh: true,
            trafficSensitivityHigh: true,
            constrainedRow: true,
            floodRisk: 'moderate',
            urbanCore: true,
            nightWorkOnly: true,
          },
          community: {
            populationCatchment: 9,
            jobCatchment: 9,
            zeroCarHouseholdsPct: 8,
            transferConnectivity: 8,
            activityNodeImportance: 9,
            heatExposureHigh: true,
            stationTransferStrong: true,
          },
        },
        {
          id: 'b-2',
          label: 'Roosevelt station zone',
          segmentType: 'station_zone',
          sectionFamily: 'fiber_reduced',
          lengthFt: 1000,
          context: 'urban_core',
          factors: {
            trafficAadt: 20000,
            intersectionDensityPerMi: 8,
            utilityDensityHigh: true,
            trafficSensitivityHigh: false,
            constrainedRow: true,
            floodRisk: 'low',
            urbanCore: true,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 9,
            jobCatchment: 8,
            zeroCarHouseholdsPct: 9,
            transferConnectivity: 9,
            activityNodeImportance: 8,
            heatExposureHigh: true,
            stationTransferStrong: true,
          },
        },
      ],
    },
    {
      id: 'alt-c',
      name: 'Alt C - Suburban Low-Cement Route',
      description: 'Lower-disruption suburban alignment with low-cement SCM-rich slab',
      geometry: buildCorridorLineGeometry('phoenix', 'alt-c'),
      segments: [
        {
          id: 'c-1',
          label: 'Bethany Home Rd at-grade (19th to 35th Ave)',
          segmentType: 'at_grade_median',
          sectionFamily: 'low_cement_rc',
          lengthFt: 8500,
          context: 'suburban',
          factors: {
            trafficAadt: 18000,
            intersectionDensityPerMi: 4,
            utilityDensityHigh: false,
            trafficSensitivityHigh: false,
            constrainedRow: false,
            floodRisk: 'low',
            urbanCore: false,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 5,
            jobCatchment: 3,
            zeroCarHouseholdsPct: 4,
            transferConnectivity: 2,
            activityNodeImportance: 3,
            heatExposureHigh: false,
            stationTransferStrong: false,
          },
        },
        {
          id: 'c-2',
          label: '35th Ave bridge approach',
          segmentType: 'bridge_approach',
          sectionFamily: 'low_cement_rc',
          lengthFt: 900,
          context: 'suburban',
          factors: {
            trafficAadt: 15000,
            intersectionDensityPerMi: 2,
            utilityDensityHigh: false,
            trafficSensitivityHigh: false,
            constrainedRow: false,
            floodRisk: 'moderate',
            urbanCore: false,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 3,
            jobCatchment: 2,
            zeroCarHouseholdsPct: 3,
            transferConnectivity: 1,
            activityNodeImportance: 2,
            heatExposureHigh: false,
            stationTransferStrong: false,
          },
        },
        {
          id: 'c-3',
          label: '35th Ave station zone',
          segmentType: 'station_zone',
          sectionFamily: 'low_cement_rc',
          lengthFt: 1100,
          context: 'suburban',
          factors: {
            trafficAadt: 12000,
            intersectionDensityPerMi: 3,
            utilityDensityHigh: false,
            trafficSensitivityHigh: false,
            constrainedRow: false,
            floodRisk: 'low',
            urbanCore: false,
            nightWorkOnly: false,
          },
          community: {
            populationCatchment: 6,
            jobCatchment: 4,
            zeroCarHouseholdsPct: 5,
            transferConnectivity: 3,
            activityNodeImportance: 4,
            heatExposureHigh: false,
            stationTransferStrong: false,
          },
        },
      ],
    },
  ],
}

export const SCENARIO_PRESETS = {
  phoenix: PHOENIX_SCENARIO,
}
